const seedData = [
  {
    "id": "P1",
    "name": "Sanjeev Kumar S",
    "teamName": "Algorythm",
    "email": "sanjeevkumaredu8@gmail.com",
    "phone": "8300122476",
    "gender": "Male",
    "memberCount": 1,
    "department": "CSE",
    "year": "II",
    "foodPreference": "Non-Veg",
    "city": "TamilNadu",
    "college": "Sri Krishna College Of Engineering And Technology",
    "projectTitle": "ThreatMesh Cyber Security"
  },
  {
    "id": "P2",
    "name": "PITTA SHANKUMAR",
    "teamName": "CodeCommit",
    "email": "shankumarpitta714@gmail.com",
    "phone": "8125983384",
    "gender": "Male",
    "memberCount": 1,
    "department": "CSE (DATA SCIENCE)",
    "year": "II",
    "foodPreference": "Non-Veg",
    "city": "HYDERABAD,TELANGANA",
    "college": "CMR COLLEGE OF ENGINEERING AND TECHNOLOGY",
    "projectTitle": "SecureNodeX"
  },
  {
    "id": "P3",
    "name": "Sevenhillsvasa S",
    "teamName": "brocode",
    "email": "sevenhillsvasasivaji@gmail.com",
    "phone": "8148358929",
    "gender": "Male",
    "memberCount": 1,
    "department": "AI&DS",
    "year": "III",
    "foodPreference": "Non-Veg",
    "city": "Trichy/ TamilNadu",
    "college": "K. Ramakrishnan College of Technology",
    "projectTitle": "Lightweight Post-Quantum Secure Messaging Framework for Resource-Constrained IoT and Mobile Devices."
  },
  {
    "id": "P4",
    "name": "Padmpriya B",
    "teamName": "ThinkShift",
    "email": "padmapriyab.aiml2024@citchennai.net",
    "phone": "9585996968",
    "gender": "Female",
    "memberCount": 1,
    "department": "CSE(AIML)",
    "year": "II",
    "foodPreference": "Non-Veg",
    "city": "Kanchipuram/ Tamilnadu",
    "college": "Chennai Institute of Technology",
    "projectTitle": "DigiDefender: Rapid Response Platform for Deepfake & NCII Protection"
  },
  {
    "id": "P5",
    "name": "jaipreethipk",
    "teamName": "Cool crew",
    "email": "jaipreethipk@gmail.com",
    "phone": "8438031139",
    "gender": "Female",
    "memberCount": 1,
    "department": "CSBS",
    "year": "II",
    "foodPreference": "Non-Veg",
    "city": "Coimbatore North, Tamil Nadu",
    "college": "Sri Eshwar College of Engineering",
    "projectTitle": "AI-Powered Phishing Detection System"
  },
  {
    "id": "P6",
    "name": "KAMEESWARA N P",
    "teamName": "spidy",
    "email": "kameeshwaran2990@gmail.com",
    "phone": "6379026829",
    "gender": "Male",
    "memberCount": 1,
    "department": "MECHANICAL",
    "year": "II",
    "foodPreference": "Non-Veg",
    "city": "Trichy / Tamil Nadu",
    "college": "K. Ramakrishnan College of Technology",
    "projectTitle": "AI IN DECEPTION: A CROSS-FORMAT PHISHING DETECTION SYSTEM"
  },
  {
    "id": "P7",
    "name": "Allen Ronalddo C",
    "teamName": "Nexus",
    "email": "allenxronaldo@gmail.com",
    "phone": "9360598180",
    "gender": "Male",
    "memberCount": 1,
    "department": "ECE",
    "year": "III",
    "foodPreference": "Non-Veg",
    "city": "Chennai,TamilNadu",
    "college": "R M K College Of Engineering and Technology",
    "projectTitle": "SPECTRA-GUARD"
  },
  {
    "id": "P9",
    "name": "Tammineni Vineesha",
    "teamName": "SentinalX",
    "email": "vineeshatammineni@gmail.com",
    "phone": "8919982877",
    "gender": "Female",
    "memberCount": 1,
    "department": "CSE",
    "year": "III",
    "foodPreference": "Veg",
    "city": "Andhra Pradesh, Vijayawada",
    "college": "KL University",
    "projectTitle": "Intelligent Honeypot for Behavioral Threat Profiling"
  },
  {
    "id": "P10",
    "name": "Dhilaga V",
    "teamName": "IT spartans",
    "email": "dhilaga23102006@gmail.com",
    "phone": "9025103681",
    "gender": "Female",
    "memberCount": 1,
    "department": "IT",
    "year": "II",
    "foodPreference": "Non-veg",
    "city": "Trichy",
    "college": "JJ College of engineering and technology",
    "projectTitle": "Real time crime navigation and alert system"
  },
  {
    "id": "P11",
    "name": "Anuja VS",
    "teamName": "Futureforge",
    "email": "av7640@srmist.edu.in",
    "phone": "7418638883",
    "gender": "Female",
    "memberCount": 1,
    "department": "Ece",
    "year": "II",
    "foodPreference": "Veg",
    "city": "Tamilnadu",
    "college": "Srm institute of science and technology",
    "projectTitle": "QRisk- Ai powered Qr and email phishing"
  },
  {
    "id": "P12",
    "name": "VEMA SARAYU",
    "teamName": "SECURE STACK",
    "email": "vemasarayu@gmail.com",
    "phone": "8885241754",
    "gender": "Female",
    "memberCount": 1,
    "department": "CSE",
    "year": "III",
    "foodPreference": "Non-veg",
    "city": "ANDHRA PRADESH",
    "college": "KL University",
    "projectTitle": "PASSWORD REUSE DETECTION"
  },
  {
    "id": "P13",
    "name": "SRI VARSHINI B",
    "teamName": "Fusion minds",
    "email": "sb7553@srmist.edu.in",
    "phone": "6380323038",
    "gender": "Female",
    "memberCount": 1,
    "department": "ECE",
    "year": "II",
    "foodPreference": "Veg",
    "city": "TAMIL NADU",
    "college": "SRM Institute of science and technology",
    "projectTitle": "Authprint : Digital Screenshot Authenticity Analyzer"
  },
  {
    "id": "P14",
    "name": "R.Hewin Sheraj Sreeman",
    "teamName": "CritAltDefend",
    "email": "2023cs0119@svce.ac.in",
    "phone": "8678944758",
    "gender": "Male",
    "memberCount": 1,
    "department": "EEE AND CSE",
    "year": "III",
    "foodPreference": "NON VEG",
    "city": "TAMILNADU",
    "college": "Sri Venkateswara College of Engineering",
    "projectTitle": "Centralized Log Monitoring and Intrusion Alert System"
  },
  {
    "id": "P1_2",
    "name": "AMIT KUMAR",
    "teamName": "Oxer",
    "email": "amitkumar911344@gmail.com",
    "phone": "8539039800",
    "gender": "Male",
    "memberCount": 1,
    "department": "CSE",
    "year": "III",
    "foodPreference": "Veg",
    "city": "MADHYA PRADESH",
    "college": "LAKSHMI NARAIN COLLEGE OF TECHNOLOGY AND SCIENCE",
    "projectTitle": "VIDUCATE - AI Powered Exam-Focused Video Learning Platform"
  },
  {
    "id": "P2_2",
    "name": "Sandhiya K",
    "teamName": "Brain wave",
    "email": "sandhiyagomathi0@gmail.com",
    "phone": "9789580934",
    "gender": "Female",
    "memberCount": 1,
    "department": "M Tech - CSE",
    "year": "II",
    "foodPreference": "Non-veg",
    "city": "Erode/ Tamil Nadu",
    "college": "Erode Sengunthar Engineering College",
    "projectTitle": "Metadata Drift Detection for AI Model Reliability Prediction"
  },
  {
    "id": "P3_2",
    "name": "Ramya N G",
    "teamName": "Fantastic Four's",
    "email": "ganesanramya05@gmail.com",
    "phone": "9445629247",
    "gender": "Female",
    "memberCount": 1,
    "department": "CSE",
    "year": "III",
    "foodPreference": "Non-veg",
    "city": "Kanchipuram, Tamil Nadu",
    "college": "University College of Engineering Kanchipuram",
    "projectTitle": "Idea & Goal: Unify all critical college info..."
  },
  {
    "id": "P4_2",
    "name": "Sanjai K",
    "teamName": "NextGen Coders",
    "email": "sanjaibtechit.official@gmail.com",
    "phone": "9363595834",
    "gender": "Male",
    "memberCount": 1,
    "department": "B.Tech IT",
    "year": "III",
    "foodPreference": "Non-Veg",
    "city": "Erode - TamilNadu",
    "college": "M.P.Nachimuthu M.Jaganathan Engineering College",
    "projectTitle": "PathPilot AI - Intelligent Career Navigation Platform"
  },
  {
    "id": "P5_2",
    "name": "Arunika N",
    "teamName": "Tech Innovators",
    "email": "arunika.n2024csbs@sece.ac.in",
    "phone": "8825981431",
    "gender": "Female",
    "memberCount": 1,
    "department": "Computer Science And Business Systems",
    "year": "II",
    "foodPreference": "Non-veg",
    "city": "Coimbatore/Tamil Nadu",
    "college": "Sri Eshwar college of engineering",
    "projectTitle": "Hear Aid"
  },
  {
    "id": "P6_2",
    "name": "PRASHANTH G",
    "teamName": "Powerhouse",
    "email": "prashanth.ad24@krct.ac.in",
    "phone": "7904264019",
    "gender": "Male",
    "memberCount": 1,
    "department": "AI&DS",
    "year": "II",
    "foodPreference": "Non-veg",
    "city": "Trichy / Tamil Nadu",
    "college": "K. Ramakrishnan College of Technology",
    "projectTitle": "Multi-Level Learning Support System for Rural Classrooms."
  },
  {
    "id": "P7_2",
    "name": "Vignesh S",
    "teamName": "Pathfinders",
    "email": "svickyvignesh141@gmail.com",
    "phone": "9345011987",
    "gender": "Male",
    "memberCount": 1,
    "department": "AI&DS",
    "year": "II",
    "foodPreference": "Non-veg",
    "city": "Chennai",
    "college": "Velammal Engineering College",
    "projectTitle": "AI-Driven Career Guidance & Student Profiling Platform"
  },
  {
    "id": "P8_2",
    "name": "Megavinayahan.V",
    "teamName": "Techno Spidey",
    "email": "megavinayahanv2006@gmail.com",
    "phone": "9025226460",
    "gender": "Male",
    "memberCount": 1,
    "department": "CSE",
    "year": "II",
    "foodPreference": "Non-veg",
    "city": "Chennai",
    "college": "Dhaanish Ahmed College Of Engineering",
    "projectTitle": "Platform for deaf and mute people"
  },
  {
    "id": "P9_2",
    "name": "SYED IRFAN AHMED",
    "teamName": "FORTUNE CODERS",
    "email": "syedirfanahmed312@gmail.com",
    "phone": "7810026278",
    "gender": "Male",
    "memberCount": 1,
    "department": "AIML",
    "year": "II",
    "foodPreference": "Non-veg",
    "city": "TAMIL NADU",
    "college": "CHENNAI INSTITUTE OF TECHNOLOGY",
    "projectTitle": "EDURA"
  },
  {
    "id": "P10_2",
    "name": "Nithiprasanna1555",
    "teamName": "FutureVolt Engineers",
    "email": "nithiprasanna1555@gmail.com",
    "phone": "9361631155",
    "gender": "Male",
    "memberCount": 1,
    "department": "BE.EEE",
    "year": "II",
    "foodPreference": "NON VEG",
    "city": "TAMILNADU",
    "college": "EXCEL ENGINEERING COLLEGE",
    "projectTitle": "Adaptive Power Management"
  },
  {
    "id": "P11_2",
    "name": "Lakshitha B",
    "teamName": "Virtual whizzes 300",
    "email": "lakshithabhaskar05@gmail.com",
    "phone": "8148952425",
    "gender": "Female",
    "memberCount": 1,
    "department": "M.tech cse (5 years)",
    "year": "IV",
    "foodPreference": "Non-veg",
    "city": "Tamil Nadu",
    "college": "Sai Ram Engineering College",
    "projectTitle": "Inclusive skill enhancer for pwd"
  }
];
